version: '3.1'
services:
  psql:
    image: library/postgres:alpine
    container_name: cs_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codesling